services:
  flask-server-1:
    build: .
    restart: always
    expose:
      - "5000"
    environment:
      SECRET_KEY: ${SECRET_KEY}
      POSTGRES_USER : ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - db
      - redis

  flask-server-2:
    build: .
    restart: always
    expose:
      - "5000"
    environment:
      SECRET_KEY: ${SECRET_KEY}
      POSTGRES_USER : ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - db
      - redis
      
  flask-server-3:
    build: .
    restart: always
    expose:
      - "5000"
    environment:
      SECRET_KEY: ${SECRET_KEY}
      POSTGRES_USER : ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:stable-perl
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask-server-1
      - flask-server-2
      - flask-server-3

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER : ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    expose:
      - "5432"
    volumes:
      - db_data_blog:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    expose:
      - "8080"

  redis:  
    image: redis
    expose:
      - "6379"

volumes:
  db_data_blog: